references:
    defaults: &defaults
      working_directory: ~/theme
      docker:
        - image: circleci/php:7.3-stretch-node-browsers

version: 2.1
jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Put server and bastion keys in file
          command: |
            echo $SSH_SERVER_KEY >> server.key
            echo $SSH_BASTION_KEY >> bastion.key
      - run:
          name: Open the SSH Tunnel
          background: true
          command: |
            ssh-keyscan 185.21.241.163 >> ~/.ssh/known_hosts
            ssh -4 -L 3000:s01.burovoordeboeg.nl:22 -i bastion.key -Nf circleci@185.21.241.163
            sleep 5
      - run:
          name: Rsync deploy to staging
          command: |
            rsync -avz -e 'ssh -p 3000 -o StrictHostKeyChecking=no -i server.key' --chown=$USER:$USER --exclude-from '.rsyncignore' . $USER@127.0.0.1:/home/$USER/domains/$PRODUCTION_PATH

workflows: 
  version: 2
  deploy:
    jobs:
      - staging:
        filters: &filter_all
          tags:
            only: /.*?/