version: 2.1

references:
    defaults: &defaults
      working_directory: ~/theme
      docker:
        - image: circleci/php:7.3-stretch-node-browsers

commands:

    # Setup the SSH keys needed to connect
    setup_ssh_keys:
      steps:
        - run:
            name: Put server and bastion keys in a file
            command: |
              echo $SSH_BASTION_KEY >> bastion.key
              echo $SSH_SERVER_KEY >> server.key
              chmod 600 bastion.key
              chmod 600 server.key
    
    # Open a SSH-tunnel
    open_ssh_tunnel:
      steps:
        - run: 
            name: Open SSH Tunnel through Bastion-host
            background: true
            command: |
              ssh-keyscan 185.21.241.163 >> ~/.ssh/known_hosts
              ssh -4 -L 3000:s01.burovoordeboeg.nl:22 -i bastion.key -Nf circleci@185.21.241.163
        - run:
            name: Wait for tunnel to setup
            command: sleep 8
    
    # Rsync deploy path specified
    rsync_deploy:
      parameters:
        environment:
          type: string
          default: ""
        path:
          type: string
          default: ""
      steps:
        - run:
            name: Rsync deploy to <<parameters.environment>>
            command: |
              if [ -z <<parameters.path>> ]
              then
                  exit 1
              fi
              rsync -avz -e "ssh -p 3000 -o StrictHostKeyChecking=no -i server.key" --chown=$USER:$USER --exclude-from '.rsyncignore' . $USER@127.0.0.1:/home/$USER/domains/<<parameters.path>>

jobs:
  production:
    <<: *defaults
    steps:
      - checkout
      - setup_ssh_keys
      - open_ssh_tunnel 
      - rsync_deploy:
          environment: Production
          path: $PRODUCTION_PATH
      
workflows:
  deploy:
    jobs:
      - production:
          name: Deploy to production
          context:
            - buro-voor-de-boeg
          filters: &filter_all
            tags:
              only: /.*?/