version: 2.1

orbs:
  dmz: eddiewebb/dmz@volatile

references:
  defaults: &defaults
    working_directory: ~/theme
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

workflows: 
  deploy:
    jobs:
      - staging:
        filters: &filter_all
          tags:
            only: /.*?/

jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - dmz/open_tunnel:
        local_port: "3000"
        target_host: "s01.burovoordeboeg.nl"
        target_port: "22"
        bastion_user: circleci
        bastion_host: 185.21.241.163
        bastion_public_key: bastion.pub
      - run:
          name: Rsync deploy to staging
          command: rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$STAGING_PATH