# ENV Variables
# $VPN_CLIENT_CONFIG = Base64 encoded OVPN

version: 2.1
workflows:
  btd:
    jobs:
      - build

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - run:
          name: Install OpenVPN and Rsync
          command: |
            sudo apt-get update
            sudo wget https://swupdate.openvpn.org/community/releases/openvpn-2.4.7.tar.gz
            sudo tar xfz openvpn-2.4.7.tar.gz
            cd openvpn-2.4.7
            sudo ./configure
            sudo make
            sudo make install
            sudo apt-get install rsync -y

      - run:
          name: Connect through VPN
          command: |
            echo $VPN_CLIENT_CONFIG | base64 --decode >> config.ovpn
            wget -qO- http://checkip.amazonaws.com | tee initial.ip
            sudo openvpn --config config.ovpn &
            while [ -n "$(ip addr show tun0 2>&1 > /dev/null)" ]; do
              sleep 0.1;
            done
            cat openvpn.log
            wget -qO- http://checkip.amazonaws.com | tee final.ip
            if [ "$(cat initial.ip)" == "$(cat final.ip)" ]
            then
              echo "This computer's apparent public IP address was not different after connecting"
              echo "This may mean that your VPN is not configured correctly."
              exit 1
            fi
    
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"

      - run:
          name: Add server keys
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

      - run:
          name: Rsync deploy to staging
          command:  rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$PRODUCTION_PATH

      - run:
          name: Disconnect from VPN
          command: sudo killall openvpn || true
          when: always

      - run:
          name: Remove OpenVPN config
          command: sudo rm config.ovpn
          when: always