# ENV Variables
# $VPN_CLIENT_CONFIG = Base64 encoded OVPN

version: 2.1
workflows:
  btd:
    jobs:
      - build

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install OpenVPN and Rsync
          command: |
            sudo apt-get update
            sudo apt-get install libssl-dev liblzo2-dev libpam0g-dev -y
            sudo wget https://swupdate.openvpn.org/community/releases/openvpn-2.4.7.tar.gz
            sudo tar xfz openvpn-2.4.7.tar.gz
            cd openvpn-2.4.7
            sudo ./configure
            sudo make
            sudo make install
            sudo apt-get install rsync -y

      - run:
          name: VPN Setup
          background: true
          command: |
            echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn
            sudo openvpn --config /tmp/config.ovpn

      - run:
          name: Wait for the connection to be established
          command: ls -la && sleep 10

      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"

      - run:
          name: Add server keys
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

      - run:
          name: Rsync deploy to staging
          command:  rsync -avzp --chown=$USER:$USER --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$PRODUCTION_PATH

      - run:
          name: Disconnect from VPN
          command: sudo killall openvpn || true
          when: always

      - run:
          name: Remove OpenVPN config
          command: sudo rm /tmp/config.ovpn
          when: always