references:
    defaults: &defaults
      working_directory: ~/theme
      docker:
        - image: circleci/php:7.3-stretch-node-browsers

    open_ssh_tunnel: &open_ssh_tunnel
      run:
        name: Open the SSH Tunnel
        background: true
        command: |
          ssh-keyscan 185.21.241.163 >> ~/.ssh/known_hosts
          ssh -L 3000:s01.burovoordeboeg.nl:22 circleci@185.21.241.163

    append_ssh_private: &append_ssh_private
      add_ssh_keys:
        fingerprints:
          - 5a:bd:a1:36:50:a0:15:b2:0c:6b:87:6f:3d:55:de:4e

    append_ssh_serverkey: &append_ssh_serverkey
      add_ssh_keys:
        fingerprints:
          - 76:d7:57:c9:86:8c:83:4e:bb:36:7f:26:41:15:4d:db

version: 2.1
jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - <<: *append_ssh_private
      - <<: *open_ssh_tunnel
      - run:
          name: Add IP to known_hosts
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - <<: *append_ssh_serverkey
      - run:
          name: Rsync deploy to staging
          command: rsync -avz -e "ssh -p3000" --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . $USER@localhost:/home/$USER/domains/$PRODUCTION_PATH

workflows: 
  version: 2
  deploy:
    jobs:
      - staging:
        filters: &filter_all
          tags:
            only: /.*?/