references:
    defaults: &defaults
      working_directory: ~/theme
      docker:
        - image: circleci/php:7.3-stretch-node-browsers
  
    open_ssh_tunnel: &open-ssh-tunnel
        name: Open a SSH Tunnel
        command: ssh -L 3000:s01.burovoordeboeg.nl:22 -i '$SSH_PUBKEY' circleci@185.21.241.163

    add_ssh_fingerprint: &add-ssh-fingerprint
      fingerprints:
        - "$SSH_FINGERPRINT"

version: 2.0
jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - open-ssh-tunnel
      - add-ssh-fingerprint
      - run:
          name: Rsync deploy to staging
          command: rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$STAGING_PATH

workflows: 
  version: 2
  deploy:
    jobs:
      - staging