references:
    defaults: &defaults
      working_directory: ~/theme
      docker:
        - image: circleci/php:7.3-stretch-node-browsers

    open_ssh_tunnel: &open_ssh_tunnel
      run:
        name: Open the SSH Tunnel
        background: true
        command: |
          ssh-keyscan 185.21.241.163 >> ~/.ssh/known_hosts
          ssh -4 -L 3000:s01.burovoordeboeg.nl:22 -Nf circleci@185.21.241.163

    append_ssh_private: &append_ssh_private
      add_ssh_keys:
        fingerprints:
          - 5a:bd:a1:36:50:a0:15:b2:0c:6b:87:6f:3d:55:de:4e

version: 2.1
jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - <<: *append_ssh_private
      - <<: *open_ssh_tunnel
      - run:
          name: Add IP to known_hosts
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      - run:
          name: sleep
          command: |
            cd ~/.ssh/
            ls -la
            sleep 10
      - run:
          name: test to put ssh server key in local file
          command: |
            ls -la
            echo $SSH_SERVER_KEY >> server.key
      - run:
          name: Rsync deploy to staging
          command: |
            rsync -avz -e 'ssh -p 3000 -o StrictHostKeyChecking=no -i server.key' --chown=$USER:$USER --exclude-from '.rsyncignore' . $USER@127.0.0.1:/home/$USER/domains/$PRODUCTION_PATH

workflows: 
  version: 2
  deploy:
    jobs:
      - staging:
        filters: &filter_all
          tags:
            only: /.*?/