version: 2.1

references:
  defaults: &defaults
    working_directory: ~/theme
    docker:
      - image: circleci/php:7.3-stretch-node-browsers

  open_ssh_tunnel: &open_ssh_tunnel
    run: 
      name: Open SSH Tunnel through Bastion-host
      background: true
      command: |
        ssh-keyscan $BASTION_IP >> ~/.ssh/known_hosts
        ssh -4 -L $BASTION_PORT:$SERVER_IP:$SERVER_PORT -Nf $BASTION_USER@$BASTION_IP

  sleep_for_ssh: &sleep_for_ssh
    run:
      name: Wait for tunnel to setup
      command: sleep 8

commands:
  rsync_deploy:
    description: Rsync deploy to input path
    parameters:
      jobname:
        type: string
        default: "production"
      path: 
        type: string
        default: ""
    steps:
      - run:
          name: Rsync deploy to <<parameters.jobname>>
          command: |
            if [ -z <<parameters.path>> ]
            then
                echo "No path specified to deploy to"
                exit 1
            fi
            rsync -avz -e "ssh -p $BASTION_PORT -o StrictHostKeyChecking=no" --chown=$USER:$USER --exclude-from '.rsyncignore' . $USER@$LOCALHOST:/home/$USER/domains/<<parameters.path>>

jobs:
  production:
    <<: *defaults
    steps:
      - checkout
      - <<: *open_ssh_tunnel 
      - <<: *sleep_for_ssh 
      - rsync_deploy:
          jobname: "production"
          path: $PRODUCTION_PATHs
      
workflows:
  deploy:
    jobs:
      - production:
          context:
            - buro-voor-de-boeg
          filters: &filter_all
            tags:
              only: /.*?/