# ENV Variables
# $VPN_CLIENT_CONFIG = Base64 encoded OVPN

version: 2.1
workflows:
  btd:
    jobs:
      - build

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install OpenVPN and Rsync
          command: |
            sudo apt-get update
            sudo apt-get install libssl-dev liblzo2-dev libpam0g-dev curl npm rsync -y
            sudo apt-get install php7.0-fpm git unzip -y
            sudo wget https://swupdate.openvpn.org/community/releases/openvpn-2.4.7.tar.gz
            sudo tar xfz openvpn-2.4.7.tar.gz
            cd openvpn-2.4.7
            sudo ./configure
            sudo make
            sudo make install
            sudo cd ~
            sudo curl -sS https://getcomposer.org/installer -o composer-setup.php
            sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    
      - run:
          name: Check IP before VPN connection
          command: |
            ifconfig
            route -n
            sudo netstat -anp
            cat /etc/resolv.conf
            curl checkip.amazonaws.com

      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
            
      - run:
          name: VPN Setup
          background: true
          command: |
            phone_home=$(netstat -an | grep ':22 .*ESTABLISHED' | head -n1 | awk '{ split($5, a, ":"); print a[1] }')
            echo $phone_home

            echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn
            sudo openvpn --config /tmp/config.ovpn \
              --route $phone_home 255.255.255.255 net_gateway \
              --route 169.254.0.0 255.255.0.0 net_gateway

      - run:
          name: Wait for the connection to be established
          command: sleep 15

      - run:
          name: Check IP after VPN connection
          command: |
            ifconfig
            route -n
            sudo netstat -anp
            cat /etc/resolv.conf
            curl checkip.amazonaws.com

      - run:
          name: Rsync deploy to staging
          command:  rsync -avzp --progress --stats --chown=$USER:$USER --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$PRODUCTION_PATH

      - run:
          name: Disconnect from VPN
          command: sudo killall openvpn || true
          when: always

      - run:
          name: Remove OpenVPN config
          command: sudo rm /tmp/config.ovpn
          when: always
