# ENV Variables
# $VPN_CLIENT_CONFIG = Base64 encoded OVPN

version: 2.1
workflows:
  btd:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    steps:
      - run:
          name: Install OpenVPN and Rsync
          command: |
            sudo apt-get update
            sudo apt-get install openvpn -y
            sudo apt-get install rsync -y

      - run:
          name: Connect through VPN
          command: |
            echo $VPN_CLIENT_CONFIG | base64 --decode >> config.ovpn
            sudo openvpn --config config.ovpn
    
      - run:
          name: Sleep while setting up connection
          command: sleep 10
    
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"

      - run:
          name: Add server keys
          command: ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts

      - run:
          name: Rsync deploy to staging
          command:  rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$PRODUCTION_PATH

      - run:
          name: Disconnect from VPN
          command: sudo killall openvpn || true
          when: always

      - run:
          name: Remove OpenVPN config
          command: sudo rm config.ovpn
          when: always