references:
    defaults: &defaults
      working_directory: ~/theme
      docker:
        - image: circleci/php:7.3-stretch-node-browsers

    open_ssh_tunnel: &open_ssh_tunnel
      run:
        name: Open the SSH Tunnel
        command: |
          ssh -L 3000:s01.burovoordeboeg.nl:22 -i '$SSH_PUBKEY' circleci@185.21.241.163

    append_sshkey: &append_sshkey
      add_ssh_keys:
        fingerprints:
          - "$SSH_FINGERPRINT"

version: 2.1
jobs:
  staging:
    <<: *defaults
    steps:
      - checkout
      - <<: *open_ssh_tunnel
      - <<: *append_sshkey
      - run:
          name: Rsync deploy to staging
          command: rsync -avzp --chown=$USER:$USER --delete --exclude-from '.rsyncignore' . $USER@$SERVER_IP:/home/$USER/domains/$STAGING_PATH

workflows: 
  version: 2
  deploy:
    jobs:
      - staging:
        filters: &filter_all
          tags:
            only: /.*?/